### ISSUE TITLE
Crashes on startup Bug

### ISSUE THREAD

**Issue by Memeruler-k** [AntiP2WDevelopment/AntiP2W-Addon#3]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-03-27 17:38:48
Description: Initializing game

java.lang.NullPointerException: Cannot read the array length because "this.values" is null
	at meteordevelopment.meteorclient.settings.EnumSetting.<init>(EnumSetting.java:29)
	at meteordevelopment.meteorclient.settings.EnumSetting$Builder.build(EnumSetting.java:73)
	at addon.antip2w.modules.PingSpoof.<init>(PingSpoof.java:38)
	at addon.antip2w.AntiP2W.registerModules(AntiP2W.java:74)
	at addon.antip2w.AntiP2W.onInitialize(AntiP2W.java:31)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:124)
	at net.minecraft.class_310.handler$cln021$meteor-client$onInit(class_310.java:23647)
	at net.minecraft.class_310.<init>(class_310.java:676)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.settings.EnumSetting.<init>(EnumSetting.java:29)
	at meteordevelopment.meteorclient.settings.EnumSetting$Builder.build(EnumSetting.java:73)
	at addon.antip2w.modules.PingSpoof.<init>(PingSpoof.java:38)
	at addon.antip2w.AntiP2W.registerModules(AntiP2W.java:74)
	at addon.antip2w.AntiP2W.onInitialize(AntiP2W.java:31)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:124)
	at net.minecraft.class_310.handler$cln021$meteor-client$onInit(class_310.java:23647)
	at net.minecraft.class_310.<init>(class_310.java:676)

**Comment by C0derK1d** [comment]
When did you get this error?

**Comment by C0derK1d** [comment]
Which meteor version did you use?

**Comment by ItsMeTomTom** [comment]
Use latest MeteorClient built.
