### ISSUE TITLE
Crashes on 1.21 (probably bc it's not updated I think but here's the error log anyways)

### ISSUE THREAD

**Issue by The-Nyla** [AntiP2WDevelopment/AntiP2W-Addon#5]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-08-04 01:32:39
Description: Initializing game

java.lang.NoSuchFieldError: Class net.minecraft.class_1893 does not have member field 'net.minecraft.class_1887 field_9118'
	at addon.antip2w.modules.ItemGenerator.<clinit>(ItemGenerator.java:628)
	at addon.antip2w.AntiP2W.registerModules(AntiP2W.java:64)
	at addon.antip2w.AntiP2W.onInitialize(AntiP2W.java:31)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:125)
	at net.minecraft.class_310.handler$ejc009$meteor-client$onInit(class_310.java:55224)
	at net.minecraft.class_310.<init>(class_310.java:706)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at addon.antip2w.modules.ItemGenerator.<clinit>(ItemGenerator.java:628)
	at addon.antip2w.AntiP2W.registerModules(AntiP2W.java:64)
	at addon.antip2w.AntiP2W.onInitialize(AntiP2W.java:31)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:125)
	at net.minecraft.class_310.handler$ejc009$meteor-client$onInit(class_310.java:55224)
	at net.minecraft.class_310.<init>(class_310.java:706)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by ghost** [comment]
Hello There! Looks like you've tried to run the addon on the minecraft version 1.21. This project has been uncontinued and stuck at 1.20.4. Thank you for your understanding.

**Comment by The-Nyla** [comment]
ah, thanks! Too bad it's been discontinued though

**Comment by 0x000006** [comment]
Fixed in v2.
